# Generated by Django 5.1.1 on 2024-10-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='National ID'),
        ),
    ]
