# Generated by Django 5.1.1 on 2024-10-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp',
            field=models.DateField(verbose_name='Expire Date'),
        ),
    ]
