# Generated by Django 5.1.1 on 2024-10-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp',
            field=models.CharField(max_length=10, verbose_name='Expire Date'),
        ),
    ]
