# Generated by Django 5.1.1 on 2024-10-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
