# Generated by Django 5.1.1 on 2024-10-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Balance'),
        ),
    ]
