# Generated by Django 5.1.1 on 2024-10-13 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_card_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Card Number')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='des_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
