# Generated by Django 5.1.1 on 2024-10-13 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_destinationcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationcard',
            name='owner',
        ),
        migrations.AddField(
            model_name='destinationcard',
            name='card_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='des_card_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinationcard',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='des_card_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
