# Generated by Django 5.1.1 on 2024-10-14 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_remove_destinationcard_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationcard',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Card Number'),
        ),
    ]
