# Generated by Django 5.1.1 on 2024-10-30 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_lastsends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastSends',
            new_name='LastSend',
        ),
    ]
