# Generated by Django 5.1.1 on 2024-10-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_rename_lastsends_lastsend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastsend',
            name='des_card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='des_card', to='card.card'),
        ),
    ]
