# Generated by Django 5.1.1 on 2024-11-01 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_lastsend_des_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Recharge', 'Recharge'), ('Internet', 'Internet'), ('Receive Money', 'Receive Money')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Successful', 'Successful'), ('Failed', 'Failed')], max_length=50, null=True)),
                ('created_at', models.CharField(max_length=100, verbose_name='Date and Time')),
                ('number', models.CharField(max_length=11, verbose_name='Number')),
                ('issue_tracking', models.CharField(max_length=12, unique=True, verbose_name='Issue Tracking')),
                ('refrence_number', models.CharField(max_length=12, unique=True, verbose_name='Refrence No')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Amount')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trans_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
