# Generated by Django 5.1.1 on 2024-11-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trans_card', to='card.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='des_card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trans_des_card', to='card.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('Recharge', 'Recharge'), ('Internet', 'Internet'), ('Receive Money', 'Receive Money'), ('Transfer', 'Transfer')], max_length=50, null=True),
        ),
    ]
