# Generated by Django 5.1.1 on 2024-11-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_remove_transaction_card_remove_transaction_des_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_card', to='card.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='des_card',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_des_card', to='card.card'),
        ),
    ]
