# Generated by Django 5.1.1 on 2024-11-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_transaction_card_transaction_des_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='des_card',
        ),
    ]
